"""empty message

Revision ID: cef4f5073acd
Revises: f735c836d7ef
Create Date: 2022-12-05 00:38:00.303162

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cef4f5073acd'
down_revision = 'f735c836d7ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('skoda_dealers', sa.Column('rating', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('skoda_dealers', 'rating')
    # ### end Alembic commands ###
