"""empty message

Revision ID: f735c836d7ef
Revises: 
Create Date: 2022-12-03 19:43:38.821892

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f735c836d7ef'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('skoda_dealers', sa.Column('country', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('skoda_dealers', 'country')
    # ### end Alembic commands ###
